### ISSUE TITLE
Instances crash with "sym_get_col_solution(): No solution has been stored!" message

### ISSUE THREAD

**Issue by JoniPulaj** [tkralphs/MibS#36]
I'm running the latest version of MibS on Ubuntu 15.10 to check some properties of small graphs that I express as pure bilevel integer programs. In default settings my instances crash with the aforementioned message. 
[GraphPebblingInstances.zip](https://github.com/tkralphs/MibS/files/1307521/GraphPebblingInstances.zip)

**Comment by tkralphs** [comment]
We are taking a look at this. In the meantime, you could try using Cbc instead of SYMPHONY (set paramter`MibS_feasCheckSolver` to `Cbc`).

**Comment by JoniPulaj** [comment]
When I set `MibS_feasCheckSolver` to `Cbc` I get a segfault. Do you get the same error?

**Comment by tkralphs** [comment]
Yes, we are seeing the same thing and working on it. Thanks!

**Comment by tkralphs** [comment]
It seems the problem is with one of the heuristics, which ew intended to be off by default. If you set `MibS_useLowerObjHeuristic, `MibS_useObjCutHeuristic` and `MibS_useWSHeuristic` all to zero, the crash should go away. We are investigating further.

**Comment by JoniPulaj** [comment]
Thank you for all your responses! Yes, setting `MibS_useLowerObjHeuristic`, `MibS_useObjCutHeuristic` and `MibS_useWSHeuristic` all to zero does make the crash go away. Unfortunately, the instances (except for the Frucht graph case where I know the optimal solution a priori) gobble up all my memory before anything of interest happens. I am slowly building up a rather small but (theoretically) interesting library of moderate size instances that I suspect will be difficult for the solver. When it's all said and done I would be happy to contribute them to your library of instances.

**Comment by tkralphs** [comment]
Yes, sure, it would be great to have some different kinds of instances, especially those from an application that are difficult for the solver. As you probably know, bilevel integer programs are very difficult to solve in general so there is a limit to what could reasonably be expected from a solver. There is much more we can do to improve MibS and we are happy to use your instances as a challenge to make it better. In addition, there are a lot of parameters that can be tweaked and different algorithmic options, so it may be possible to improve things with just some parameter tuning. By the way, you can also use CPLEX as the underlying solver if you happen to have a CPLEX license around. That would already probably improve things.

**Comment by JoniPulaj** [comment]
I do have a CPLEX academic license. When I set `MibS_feasCheckSolver` to `CPLEX` I get an error that says "CPLEX chosen as a solver, but it has not been enabled".  What do I have to do to enable CPLEX?

**Comment by tkralphs** [comment]
Oops, look like I lost track of this conversation. When you build MibS, you need to pass the configure arguments to tell it where to find CPLEX. These arguments are passed to Osi, which then builds OsiCpx. If MibS detects OsiCpx, then it will automatically enable CPLEX. Something like this should work
```
BuildTools/get.dependencies build --quiet --with-cplex-lib="-L/usr/local/CPLEX_Studio_125/cplex/lib/x86-64_sles10_4.1/static_pic/ -lcplex -lpthread -lm" --with-cplex-incdir=/usr/local/CPLEX_Studio_125/cplex/include/ilcplex
```
If you're still out there and this doesn't work, let me know.

**Comment by JoniPulaj** [comment]
Yes it works now. Thanks!
